# Generated by Django 3.2.9 on 2021-11-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningportal', '0003_auto_20211127_0133'),
    ]

    # operations = [
    #     migrations.RemoveConstraint(
    #         model_name='watchlistitem',
    #         name='watchlist_cant_repeat',
    #     ),
    # ]
