# Generated by Django 3.2.9 on 2021-11-27 03:22

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learningportal', '0005_auto_20211127_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('date_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact form records',
            },
        ),
    ]
