# Generated by Django 3.2.9 on 2021-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningportal', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
